/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.CursoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.DisciplinaDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.ProfessorDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.ProfessorDisciplinaDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Curso;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Disciplina;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Professor;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.ProfessorDisciplinas;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author Maike Jordan
 */
public class frmCadProfessorDisciplina extends javax.swing.JInternalFrame {

    private List<Curso> cursos;
    private CursoDAO cursodao;
    private Professor professor;
    private List<Disciplina> disciplinas;
    private DisciplinaDAO disciplinadao;
    private ProfessorDAO professordao;
    private List<ProfessorDisciplinas> professordisciplina;
    private ProfessorDisciplinaDAO professordisciplinadao;

    /**
     * Creates new form frmCadProfessorDisciplina
     */
    public frmCadProfessorDisciplina(int cod) {
        initComponents();

        cursodao = new CursoDAO();
        disciplinadao = new DisciplinaDAO();
        professordao = new ProfessorDAO();
        professordisciplina = new LinkedList<>();
        professordisciplinadao = new ProfessorDisciplinaDAO();

        cursos = cursodao.ListarTodos();

        cbxcurso.removeAllItems();
        for (Curso curso : cursos) {
            cbxcurso.addItem(curso);
        }
        
        
        cbxdisciplina.removeAllItems();
        for (Disciplina disciplina :  disciplinas){
            cbxdisciplina.addItem(disciplina);
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurso = new javax.swing.JLabel();
        cbxcurso = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbxdisciplina = new javax.swing.JComboBox();
        lblDisciplina = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblEmenta = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblDuracao = new javax.swing.JLabel();
        lblTextoduracao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        lblMeses = new javax.swing.JLabel();

        setTitle("Disciplinas do Professor");

        lblCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurso.setText("SELECIONE O CURSO: ");

        cbxcurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcursoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cbxdisciplina.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        cbxdisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxdisciplinaActionPerformed(evt);
            }
        });

        lblDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDisciplina.setText("SELECIONE A DISCIPLINA:");

        jButton1.setText("Adicionar");

        lblEmenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmenta.setText("EMENTA DA DISCIPLINA:");

        jButton2.setText("Remover");

        lblDuracao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDuracao.setText("DURAÇÃO DO CURSO:");

        lblTextoduracao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        lblMeses.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMeses.setText("MESES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCurso)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbxcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblDuracao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTextoduracao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblMeses)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDisciplina)
                                    .addComponent(lblEmenta))
                                .addGap(18, 18, 18)
                                .addComponent(cbxdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(cbxcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDisciplina))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmenta)
                    .addComponent(lblDuracao)
                    .addComponent(lblTextoduracao))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMeses))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbxdisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxdisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxdisciplinaActionPerformed

    private void cbxcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcursoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxcursoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxcurso;
    private javax.swing.JComboBox cbxdisciplina;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblDuracao;
    private javax.swing.JLabel lblEmenta;
    private javax.swing.JLabel lblMeses;
    private javax.swing.JLabel lblTextoduracao;
    // End of variables declaration//GEN-END:variables
}
