/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.BD;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.UsuarioDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Funcionario;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class frmCadUsuario extends javax.swing.JInternalFrame {
    private BD bd;
    private UsuarioDAO usuariodao;
    private Usuario usuario;
    private Funcionario funcionario;
    /**
     * Creates new form frmCadUsuario
     */
    public frmCadUsuario(int cod) {
        initComponents();
        usuariodao = new UsuarioDAO();
        funcionario = new Funcionario();
        funcionario.setCodfuncionario(cod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoLogin = new javax.swing.JLabel();
        txtNovoLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        pfNovaSenha = new javax.swing.JPasswordField();
        lblSenhaNovamente = new javax.swing.JLabel();
        pfNovaSenhaNov = new javax.swing.JPasswordField();
        btnCadastrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Usuário");

        lblNovoLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNovoLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNovoLogin.setText("LOGIN:");

        txtNovoLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNovoLogin.setToolTipText("");

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSenha.setText("SENHA:");

        pfNovaSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblSenhaNovamente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenhaNovamente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSenhaNovamente.setText("DIGITE A NOVA SENHA NOVAMENTE:");

        pfNovaSenhaNov.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnCadastrar.setBackground(new java.awt.Color(98, 155, 88));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_confirm.fw.png"))); // NOI18N
        btnCadastrar.setText("  Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(183, 70, 53));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cancel.fw.png"))); // NOI18N
        btnCancelar.setText("  Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenhaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfNovaSenhaNov, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtNovoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNovoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(483, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNovoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNovaSenhaNov, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblNovoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Cadastrar o Usuário?") == 0){
            if (pfNovaSenha.getText().equals(pfNovaSenhaNov.getText())){
                usuario = new Usuario();
                usuario.setLogin(txtNovoLogin.getText());
                usuario.setSenha(pfNovaSenha.getText());
                usuario.setFuncionario(funcionario);
                if (usuariodao.Salvar(usuario)){
                    JOptionPane.showMessageDialog(rootPane, "Usuário Cadastrado com Sucesso!");
                    this.dispose();
                    frmListaFuncionario janela = new frmListaFuncionario();
                    add(janela);
                    janela.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Senha Incorreta!");
                pfNovaSenha.setFocusable(true);
                pfNovaSenhaNov.setFocusable(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cadastro Cancelado!");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja cancelar o cadastro?") == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblNovoLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaNovamente;
    private javax.swing.JPasswordField pfNovaSenha;
    private javax.swing.JPasswordField pfNovaSenhaNov;
    private javax.swing.JTextField txtNovoLogin;
    // End of variables declaration//GEN-END:variables
}
