/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.BD;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.UsuarioDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class frmEditarUsuario extends javax.swing.JInternalFrame {
    BD bd;
    UsuarioDAO usuariodao;
    Usuario usuario;
    
    /**
     * Creates new form frmAlterarUsuario
     */
    public frmEditarUsuario(int cod) {
        initComponents();
        usuariodao = new UsuarioDAO();
        usuario = usuariodao.Abrir(cod);
        txtLoginAtual.setText(usuario.getLogin());
        pfSenhaAtual.setText(usuario.getSenha());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoLogin = new javax.swing.JLabel();
        txtNovoLogin = new javax.swing.JTextField();
        lblSenhaAtual = new javax.swing.JLabel();
        pfSenhaAtual = new javax.swing.JPasswordField();
        btnAtualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblSenha = new javax.swing.JLabel();
        pfNovaSenha = new javax.swing.JPasswordField();
        lblSenhaNovamente = new javax.swing.JLabel();
        pfNovaSenhaNov = new javax.swing.JPasswordField();
        lblLoginAtual = new javax.swing.JLabel();
        txtLoginAtual = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Editar Usuário");

        lblNovoLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNovoLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNovoLogin.setText(" NOVO LOGIN:");

        txtNovoLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNovoLogin.setToolTipText("");

        lblSenhaAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenhaAtual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenhaAtual.setText("SENHA ATUAL:");

        pfSenhaAtual.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnAtualizar.setBackground(new java.awt.Color(98, 155, 88));
        btnAtualizar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_confirm.fw.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(183, 70, 53));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cancel.fw.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenha.setText("NOVA SENHA:");

        pfNovaSenha.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblSenhaNovamente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSenhaNovamente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSenhaNovamente.setText("DIGITE A NOVA SENHA NOVAMENTE:");

        pfNovaSenhaNov.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblLoginAtual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLoginAtual.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoginAtual.setText(" LOGIN ATUAL:");

        txtLoginAtual.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtLoginAtual.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSenhaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfNovaSenhaNov, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNovoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLoginAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(lblSenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfSenhaAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoginAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNovoLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLoginAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNovoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaNovamente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfNovaSenhaNov, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja Atualizar o usuário?") == 0){
            if (pfNovaSenha.getText().equals(pfNovaSenhaNov.getText())){
                usuario.setLogin(txtNovoLogin.getText());
                usuario.setSenha(pfNovaSenha.getText());
                if (usuariodao.Salvar(usuario))
                    JOptionPane.showMessageDialog(rootPane, "Usuário Atualizado com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Senha Incorreta!");
                pfNovaSenha.setFocusable(true);
                pfNovaSenhaNov.setFocusable(true);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Atualização Cancelada!");
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(rootPane, "Deseja cancelar a atualização?") == 0){
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblLoginAtual;
    private javax.swing.JLabel lblNovoLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSenhaAtual;
    private javax.swing.JLabel lblSenhaNovamente;
    private javax.swing.JPasswordField pfNovaSenha;
    private javax.swing.JPasswordField pfNovaSenhaNov;
    private javax.swing.JPasswordField pfSenhaAtual;
    private javax.swing.JTextField txtLoginAtual;
    private javax.swing.JTextField txtNovoLogin;
    // End of variables declaration//GEN-END:variables
}
