/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.MedidaTempoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.RecursoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.TiporecursoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.MedidaTempo;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Recurso;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.TipoRecurso;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauro
 */
public class frmListaRecursos extends javax.swing.JInternalFrame {
      
        
      private List<Recurso> recursos;
      private List<MedidaTempo> medidastempo;
      private List<TipoRecurso> tiposrecurso;
      private RecursoDAO recursodao;
      private TiporecursoDAO tiporecursodao;
      private MedidaTempoDAO medidatempodao;
    /**
     * Creates new form frmListaRecursos
     */
    public frmListaRecursos() {
        initComponents();
        recursodao = new RecursoDAO();
        medidatempodao = new MedidaTempoDAO();
        tiporecursodao = new TiporecursoDAO();
        recursos = recursodao.ListarTodos();
        tiposrecurso = tiporecursodao.ListarTodos();
        medidastempo = medidatempodao.ListarTodos();
        
        preenchetabela(recursos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        cbxfiltro_secundario = new javax.swing.JComboBox();
        btnBuscarRecursos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaRecursos = new javax.swing.JTable();
        btnAlterarRecursos = new javax.swing.JButton();
        btnRemoverRecursos = new javax.swing.JButton();
        cbxfiltro = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Recursos");

        cbxfiltro_secundario.setEnabled(false);

        btnBuscarRecursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarRecursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_busca.fw.png"))); // NOI18N
        btnBuscarRecursos.setText("  Buscar");
        btnBuscarRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRecursosActionPerformed(evt);
            }
        });

        tblListaRecursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListaRecursos);

        btnAlterarRecursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarRecursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.fw.png"))); // NOI18N
        btnAlterarRecursos.setText("  Alterar");
        btnAlterarRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarRecursosActionPerformed(evt);
            }
        });

        btnRemoverRecursos.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverRecursos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverRecursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverRecursos.setText("  Remover ");
        btnRemoverRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRecursosActionPerformed(evt);
            }
        });

        cbxfiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome", "Descrição", "Nº Patrimônio", "Capacidade", "Medida Tempo", "Tipo de Recurso" }));
        cbxfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfiltroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxfiltro_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 782, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlterarRecursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarRecursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxfiltro_secundario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnAlterarRecursos)
                        .addGap(51, 51, 51)
                        .addComponent(btnRemoverRecursos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  private void preenchetabela(List<Recurso> recursos){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("Descrição");
        model.addColumn("N° Patrimônio");
        model.addColumn("Capacidade");
        model.addColumn("Tempo");
        model.addColumn("Medida Tempo");
        model.addColumn("Tipo Recurso");
        
        for(Recurso recurso : recursos){
            Vector v = new Vector();
            recurso.setMedidatempo(medidatempodao.Abrir(recurso.getMedidatempo().getCodtempomaximo()));
            recurso.setTiporecurso(tiporecursodao.Abrir(recurso.getTiporecurso().getCodtiporecurso()));
            v.add(0, recurso.getCodrecurso());
            v.add(1, recurso);
            v.add(2, recurso.getDescricao());
            v.add(3, recurso.getNum_patrimonio());
            v.add(4, recurso.getCapacidade());
            v.add(5, recurso.getTempo());
            v.add(6, recurso.getMedidatempo());
            v.add(7, recurso.getTiporecurso());
            model.addRow(v);
        }
        
        tblListaRecursos.setModel(model);
     
    }
    private void btnBuscarRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRecursosActionPerformed
        // TODO add your handling code here:
        Recurso recurso = new Recurso();
        
        if (cbxfiltro.getSelectedIndex() == 0){
            recurso.setCodrecurso(Integer.parseInt(txtFiltro.getText()));
        }
        
        if (cbxfiltro.getSelectedIndex() == 1){
            recurso.setNome(txtFiltro.getText());
        }
        
        if (cbxfiltro.getSelectedIndex() == 2){
            recurso.setDescricao(txtFiltro.getText());
        }
        
        if (cbxfiltro.getSelectedIndex() == 3){
            recurso.setNum_patrimonio(Integer.parseInt(txtFiltro.getText()));
        }
        
        if (cbxfiltro.getSelectedIndex() == 4){
            recurso.setCapacidade(Integer.parseInt(txtFiltro.getText()));
        }
        
        if (cbxfiltro.getSelectedIndex() == 5){
            recurso.setTempo(Integer.parseInt(txtFiltro.getText()));
            recurso.setMedidatempo((MedidaTempo) cbxfiltro_secundario.getSelectedItem());
        }
        
        if (cbxfiltro.getSelectedIndex() == 6){
            recurso.setTiporecurso((TipoRecurso) cbxfiltro_secundario.getSelectedItem());
        }
        
        recursos = recursodao.BuscarRecurso(recurso);
        
        preenchetabela(recursos);

    }//GEN-LAST:event_btnBuscarRecursosActionPerformed

    private void btnAlterarRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarRecursosActionPerformed
        // TODO add your handling code here:
        if (tblListaRecursos.getSelectedRow() >= 0){
            Recurso recurso = (Recurso) tblListaRecursos.getValueAt(tblListaRecursos.getSelectedRow(), 1);
            frmEditarRecurso janela = new frmEditarRecurso(recurso.getCodrecurso());
            this.getParent().add(janela);
            janela.setVisible(true);
            this.setVisible(false);            
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Recurso por favor!");
        }
    }//GEN-LAST:event_btnAlterarRecursosActionPerformed

    private void btnRemoverRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRecursosActionPerformed
        // TODO add your handling code here:
        if (tblListaRecursos.getSelectedRow() >= 0){
            recursos = recursodao.ListarTodos();
            Recurso recurso = (Recurso) tblListaRecursos.getValueAt(tblListaRecursos.getSelectedRow(), 1);
            if(recursodao.Apagar(recurso.getCodrecurso())){
                recursos.remove(recurso);
                JOptionPane.showMessageDialog(rootPane, "Recurso removido com Sucesso!");
            }
            preenchetabela(recursos);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Recurso por favor!");
        }
    }//GEN-LAST:event_btnRemoverRecursosActionPerformed

    private void cbxfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfiltroActionPerformed
        // TODO add your handling code here:
        if (cbxfiltro.getSelectedIndex() == 5){
            cbxfiltro_secundario.setEnabled(true);
            
            cbxfiltro_secundario.removeAllItems();
            for(MedidaTempo medidatempo: medidastempo){
                cbxfiltro_secundario.addItem(medidatempo);
            }
        }
        
        if (cbxfiltro.getSelectedIndex() == 6){
            cbxfiltro_secundario.setEnabled(true);
            
            cbxfiltro_secundario.removeAllItems();
            for(TipoRecurso tiporecurso :  tiposrecurso){
                cbxfiltro_secundario.addItem(tiporecurso);
            }
            
            txtFiltro.setEnabled(false);
        
        }
        
        if (cbxfiltro.getSelectedIndex() != 5 && cbxfiltro.getSelectedIndex() != 6){
            cbxfiltro_secundario.setEnabled(false);
        }
        
        if (cbxfiltro.getSelectedIndex() != 6){
            txtFiltro.setEnabled(true);
            
        }
    }//GEN-LAST:event_cbxfiltroActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarRecursos;
    private javax.swing.JButton btnBuscarRecursos;
    private javax.swing.JButton btnRemoverRecursos;
    private javax.swing.JComboBox cbxfiltro;
    private javax.swing.JComboBox cbxfiltro_secundario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaRecursos;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
