/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.BD;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.EmailDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.EnderecoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.FuncionarioDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.PessoaDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.TelefoneDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.UsuarioDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Email;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Endereco;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Funcionario;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Pessoa;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Telefone;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Usuario;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class frmListaFuncionario extends javax.swing.JInternalFrame {
    private BD bd;
    private Usuario usuario;
    private List<Funcionario> funcionarios;
    private Pessoa pessoa;
    private PessoaDAO pessoadao;
    private EmailDAO emaildao;
    private EnderecoDAO enderecodao;
    private TelefoneDAO telefonedao;
    private FuncionarioDAO funcionariodao;
    private UsuarioDAO usuariodao;
    
    
    /**
     * Creates new form frmListaFuncionario
     */
    public frmListaFuncionario() {
        initComponents();
        funcionariodao = new FuncionarioDAO();
        usuariodao = new UsuarioDAO();
        pessoadao = new PessoaDAO();
        enderecodao = new EnderecoDAO();
        emaildao = new EmailDAO();
        telefonedao = new TelefoneDAO();
        funcionarios = funcionariodao.ListarTodos();
        preenchetabela(funcionarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFiltro = new javax.swing.JTextField();
        cbxfiltro = new javax.swing.JComboBox();
        btnBuscarFuncionario = new javax.swing.JButton();
        btnAlterarFuncionario = new javax.swing.JButton();
        btnRemoverFuncionario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnRemoverUsuario = new javax.swing.JButton();
        btnAdicionarUsuario = new javax.swing.JButton();
        btnAlterarUsuario = new javax.swing.JButton();
        btnVisualizarSecoes = new javax.swing.JButton();

        setClosable(true);
        setTitle("Lista de Funcionários");
        setToolTipText("");

        cbxfiltro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxfiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "  Código", "  Nome", "  RG", "  CPF", "  Siape", "  Cargo" }));
        cbxfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxfiltroActionPerformed(evt);
            }
        });

        btnBuscarFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_busca.fw.png"))); // NOI18N
        btnBuscarFuncionario.setText("  Buscar");
        btnBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFuncionarioActionPerformed(evt);
            }
        });

        btnAlterarFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.fw.png"))); // NOI18N
        btnAlterarFuncionario.setText("  Alterar");
        btnAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarFuncionarioActionPerformed(evt);
            }
        });

        btnRemoverFuncionario.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverFuncionario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverFuncionario.setText("  Remover Funcionário");
        btnRemoverFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverFuncionarioActionPerformed(evt);
            }
        });

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "RG", "CPF", "Siape", "Cargo"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        btnRemoverUsuario.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverUsuario.setText("  Remover Usuário");
        btnRemoverUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverUsuarioActionPerformed(evt);
            }
        });

        btnAdicionarUsuario.setBackground(new java.awt.Color(98, 155, 88));
        btnAdicionarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_add.fw.png"))); // NOI18N
        btnAdicionarUsuario.setText("  Adicionar Usuário");
        btnAdicionarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarUsuarioActionPerformed(evt);
            }
        });

        btnAlterarUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.fw.png"))); // NOI18N
        btnAlterarUsuario.setText("  Alterar Usuário");
        btnAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarUsuarioActionPerformed(evt);
            }
        });

        btnVisualizarSecoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnVisualizarSecoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_visualizar.fw.png"))); // NOI18N
        btnVisualizarSecoes.setText("Visualizar Seções");
        btnVisualizarSecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarSecoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFiltro)
                        .addGap(18, 18, 18)
                        .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoverFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdicionarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVisualizarSecoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAlterarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoverFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnAdicionarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(btnVisualizarSecoes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoverUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void preenchetabela(List<Funcionario> funcionarios){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("RG");
        model.addColumn("CPF");
        model.addColumn("SIAPE");
        model.addColumn("Cargo");
        model.addColumn("Usuário");
        for (Funcionario funcionario : funcionarios){
            Vector v = new Vector();
            pessoa = new Pessoa();
            pessoa = pessoadao.Abrir(funcionario.getCodpessoa());
            funcionario.setPessoa(pessoa);
            int us = usuariodao.VerificaUsuario(funcionario.getCodfuncionario());
            v.add(0, funcionario.getCodfuncionario());
            v.add(1, funcionario);
            v.add(2, pessoa.getRg());
            v.add(3, pessoa.getCpf());
            v.add(4, funcionario.getSiape());
            v.add(5, funcionario.getCargo());
            if (us > 0){
                v.add(6, "Sim");
            } else {
                v.add(6, "Não");
            }
            model.addRow(v);
        }
        
        tblFuncionarios.setModel(model);
    }
    
    private void cbxfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxfiltroActionPerformed

    private void btnBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFuncionarioActionPerformed
        // TODO add your handling code here:
        Funcionario funcionario = new Funcionario();
        Pessoa pessoa = new Pessoa();

        if (cbxfiltro.getSelectedIndex() == 0){
            funcionario.setCodfuncionario(Integer.parseInt(txtFiltro.getText()));
            funcionario.setPessoa(pessoa);
        }

        if (cbxfiltro.getSelectedIndex() == 1){
            pessoa.setNome(txtFiltro.getText());
            funcionario.setPessoa(pessoa);
        }

        if (cbxfiltro.getSelectedIndex() == 2){
            pessoa.setRg(txtFiltro.getText());
            funcionario.setPessoa(pessoa);
        }

        if (cbxfiltro.getSelectedIndex() == 3){
            pessoa.setCpf(Integer.parseInt(txtFiltro.getText()));
            funcionario.setPessoa(pessoa);
        }

        if (cbxfiltro.getSelectedIndex() == 4){
            funcionario.setSiape(txtFiltro.getText());
            funcionario.setPessoa(pessoa);
        }

        if (cbxfiltro.getSelectedIndex() == 5){
            funcionario.setCargo(txtFiltro.getText());
            funcionario.setPessoa(pessoa);
        }

        List<Funcionario> funcionarios2 = funcionariodao.BuscarFuncionario(funcionario);
        List<Pessoa> pessoas = pessoadao.BuscarPessoa(funcionario.getPessoa());
        List<Funcionario> func = new LinkedList<>();

        for (Funcionario fu : funcionarios2){
            for (Pessoa pe : pessoas){
                if (fu.getCodpessoa() == pe.getCodpessoa()){
                    fu.setPessoa(pe);
                    func.add(fu);
                }
            }
        }

        preenchetabela(func);

    }//GEN-LAST:event_btnBuscarFuncionarioActionPerformed

    private void btnAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarFuncionarioActionPerformed
        // TODO add your handling code here:
        if (tblFuncionarios.getSelectedRow() >= 0){

            Funcionario funcionario = (Funcionario) tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1);
            frmEditarFuncionario janela = new frmEditarFuncionario(funcionario.getCodfuncionario());
            this.getParent().add(janela);
            janela.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário por favor!");
        }
    }//GEN-LAST:event_btnAlterarFuncionarioActionPerformed

    private void btnRemoverFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverFuncionarioActionPerformed
        // TODO add your handling code here:
        if (tblFuncionarios.getSelectedRow() >=0){

            funcionarios = new LinkedList<>();
            funcionarios = funcionariodao.ListarTodos();
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Apagar esse Professor?") == 0){
                Funcionario funcionario = (Funcionario) tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1);

                pessoa = pessoadao.Abrir(funcionario.getCodpessoa());
                pessoa.setEmails(emaildao.Abrir(funcionario.getCodpessoa()));
                pessoa.setEnderecos(enderecodao.Abrir(funcionario.getCodpessoa()));
                pessoa.setTelefones(telefonedao.Abrir(funcionario.getCodpessoa()));

                for (Endereco en : pessoa.getEnderecos()){
                    enderecodao.Apagar(en.getCodendereco());
                }

                for (Telefone tel : pessoa.getTelefones()){
                    telefonedao.Apagar(tel.getCodtelefone());
                }

                for (Email em : pessoa.getEmails()){
                    emaildao.Apagar(em.getCodemail());
                }

                if (funcionariodao.Apagar(funcionario.getCodfuncionario()) && pessoadao.Apagar(pessoa.getCodpessoa())){
                    funcionarios.remove(funcionario);
                    JOptionPane.showMessageDialog(rootPane, "Funcionário com Sucesso!");
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Ação Cancelada!");
            }

            preenchetabela(funcionarios);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário por favor!");
        }
    }//GEN-LAST:event_btnRemoverFuncionarioActionPerformed

    private void btnRemoverUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverUsuarioActionPerformed
        // TODO add your handling code here:
        if (tblFuncionarios.getSelectedRow() >= 0){
            Funcionario funcionario = (Funcionario) tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1);
            if (usuariodao.VerificaUsuario(funcionario.getCodfuncionario()) > 0){
                int us = usuariodao.VerificaUsuario(funcionario.getCodfuncionario());
                if(usuariodao.Apagar(us))
                JOptionPane.showMessageDialog(rootPane, "Usuário Apagado com Sucesso!");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Este funcionário não possui um usuário!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário por favor!");
        }
    }//GEN-LAST:event_btnRemoverUsuarioActionPerformed

    private void btnAdicionarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarUsuarioActionPerformed
        // TODO add your handling code here:
        if (tblFuncionarios.getSelectedRow() >= 0){
            Funcionario funcionario = (Funcionario) tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1);
            if (usuariodao.VerificaUsuario(funcionario.getCodfuncionario()) == 0){
                frmCadUsuario janela = new frmCadUsuario(funcionario.getCodfuncionario());
                this.getParent().add(janela);
                janela.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Este funcionário já possui um usuário!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário por favor!");
        }
    }//GEN-LAST:event_btnAdicionarUsuarioActionPerformed

    private void btnAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarUsuarioActionPerformed
        // TODO add your handling code here:
        if (tblFuncionarios.getSelectedRow() >= 0){
            Funcionario funcionario = (Funcionario) tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1);
            if (usuariodao.VerificaUsuario(funcionario.getCodfuncionario()) > 0){
                int us = usuariodao.VerificaUsuario(funcionario.getCodfuncionario());
                frmEditarUsuario janela = new frmEditarUsuario(us);
                this.getParent().add(janela);
                janela.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Este funcionário não possui um usuário!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário por favor!");
        }
        
    }//GEN-LAST:event_btnAlterarUsuarioActionPerformed

    private void btnVisualizarSecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarSecoesActionPerformed
        // TODO add your handling code here:
        if (tblFuncionarios.getSelectedRow() >= 0){
            Funcionario funcionario = (Funcionario) tblFuncionarios.getValueAt(tblFuncionarios.getSelectedRow(), 1);
            if (usuariodao.VerificaUsuario(funcionario.getCodfuncionario()) > 0){
                int us = usuariodao.VerificaUsuario(funcionario.getCodfuncionario());
                frmSecoes janela = new frmSecoes(us);
                this.getParent().add(janela);
                janela.setVisible(true);
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Este funcionário não possui um usuário!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Funcionário por favor!");
        }
        
    }//GEN-LAST:event_btnVisualizarSecoesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarUsuario;
    private javax.swing.JButton btnAlterarFuncionario;
    private javax.swing.JButton btnAlterarUsuario;
    private javax.swing.JButton btnBuscarFuncionario;
    private javax.swing.JButton btnRemoverFuncionario;
    private javax.swing.JButton btnRemoverUsuario;
    private javax.swing.JButton btnVisualizarSecoes;
    private javax.swing.JComboBox cbxfiltro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
