/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.TiporecursoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.TipoRecurso;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mauro
 */
public class frmListaTiporecurso extends javax.swing.JInternalFrame {
    
    private List<TipoRecurso> tiposrecurso;
    private TiporecursoDAO tiporecursodao;
    /**
     * Creates new form frmListaTiporecurso
     */
    public frmListaTiporecurso() {
        initComponents();
        tiporecursodao = new TiporecursoDAO();
        tiposrecurso = tiporecursodao.ListarTodos();
        
        preenchetabela(tiposrecurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        txtFiltro = new javax.swing.JTextField();
        cbxFiltro = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaTiporecurso = new javax.swing.JTable();
        btnBuscarTiporecurso = new javax.swing.JButton();
        btnAlterarTiporecurso = new javax.swing.JButton();
        btnRemoverTiporecurso = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Tipos de Recurso");

        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Código", "Nome", "Descrição" }));

        tblListaTiporecurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblListaTiporecurso);

        btnBuscarTiporecurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarTiporecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_busca.fw.png"))); // NOI18N
        btnBuscarTiporecurso.setText("  Buscar");
        btnBuscarTiporecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTiporecursoActionPerformed(evt);
            }
        });

        btnAlterarTiporecurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAlterarTiporecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_editar.fw.png"))); // NOI18N
        btnAlterarTiporecurso.setText("  Alterar");
        btnAlterarTiporecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarTiporecursoActionPerformed(evt);
            }
        });

        btnRemoverTiporecurso.setBackground(new java.awt.Color(98, 155, 88));
        btnRemoverTiporecurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemoverTiporecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemoverTiporecurso.setText("  Remover ");
        btnRemoverTiporecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTiporecursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFiltro)
                        .addGap(27, 27, 27)
                        .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAlterarTiporecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscarTiporecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoverTiporecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnBuscarTiporecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAlterarTiporecurso)
                        .addGap(51, 51, 51)
                        .addComponent(btnRemoverTiporecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void preenchetabela(List<TipoRecurso> tiposrecurso){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Código");
        model.addColumn("Nome");
        model.addColumn("Descrição");
        
        for(TipoRecurso tipos : tiposrecurso){
            Vector v = new Vector();
            v.add(0, tipos.getCodtiporecurso());
            v.add(1, tipos);
            v.add(2, tipos.getDescricao());
            model.addRow(v);
        }
        
        tblListaTiporecurso.setModel(model);
     
    }
    
    private void btnBuscarTiporecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTiporecursoActionPerformed
        // TODO add your handling code here:
        
        TipoRecurso tiporecurso = new TipoRecurso();

        if (cbxFiltro.getSelectedIndex() == 0){
            tiporecurso.setCodtiporecurso(Integer.parseInt(txtFiltro.getText()));
        }

        if (cbxFiltro.getSelectedIndex() == 1){
            tiporecurso.setNome(txtFiltro.getText());
           
        }

        if (cbxFiltro.getSelectedIndex() == 2){
            tiporecurso.setDescricao(txtFiltro.getText());
            
        }

        List<TipoRecurso> tiposrecurso = tiporecursodao.BuscarTipoRecurso(tiporecurso);       

        preenchetabela(tiposrecurso);
    }//GEN-LAST:event_btnBuscarTiporecursoActionPerformed

    private void btnAlterarTiporecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarTiporecursoActionPerformed
        // TODO add your handling code here:
        if (tblListaTiporecurso.getSelectedRow() >= 0){
            
            TipoRecurso tiporecurso = (TipoRecurso) tblListaTiporecurso.getValueAt(tblListaTiporecurso.getSelectedRow(), 1);
            frmEditarTiporecurso janela = new frmEditarTiporecurso(tiporecurso.getCodtiporecurso());
            this.getParent().add(janela);
            janela.setVisible(true);
            this.setVisible(false);
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Tipo de Recurso por favor!");
        }
    }//GEN-LAST:event_btnAlterarTiporecursoActionPerformed

    private void btnRemoverTiporecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTiporecursoActionPerformed
        // TODO add your handling code here:
        if (tblListaTiporecurso.getSelectedRow() >= 0){
            
            List<TipoRecurso> tiposrecurso = tiporecursodao.ListarTodos();
            TipoRecurso tiporecurso = (TipoRecurso) tblListaTiporecurso.getValueAt(tblListaTiporecurso.getSelectedRow(), 1);
            tiporecursodao.Apagar(tiporecurso.getCodtiporecurso());
            tiposrecurso.remove(tiporecurso);
            preenchetabela(tiposrecurso);
            
            JOptionPane.showMessageDialog(rootPane, "Tipo de Recurso Removido com Sucesso!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um Tipo de Recurso por favor!");
        }
    }//GEN-LAST:event_btnRemoverTiporecursoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarTiporecurso;
    private javax.swing.JButton btnBuscarTiporecurso;
    private javax.swing.JButton btnRemoverTiporecurso;
    private javax.swing.JComboBox cbxFiltro;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaTiporecurso;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
