/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.tads.trabalhofinal.InterfaceUsuario;

import br.edu.ifnmg.tads.trabalhofinal.DataAccess.CursoDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.DisciplinaDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.PessoaDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.ProfessorDAO;
import br.edu.ifnmg.tads.trabalhofinal.DataAccess.ProfessorDisciplinaDAO;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Curso;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Disciplina;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Pessoa;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.Professor;
import br.edu.ifnmg.tads.trabalhofinal.DoMainModel.ProfessorDisciplinas;
import java.awt.Component;
import java.util.LinkedList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maike Jordan
 */
public class frmProfessorDisciplina extends javax.swing.JInternalFrame {
   
    private Component RootPane;
    private List<Curso> cursos;
    private CursoDAO cursodao;
    private Professor professor;
    private DisciplinaDAO disciplinadao;
    private ProfessorDAO professordao;
    private List<ProfessorDisciplinas> professordisciplinas;
    private ProfessorDisciplinaDAO professordisciplinadao;
    private PessoaDAO pessoadao;
    private Curso curso;
    private Disciplina disciplina;
    private Pessoa pessoa;
    private List<ProfessorDisciplinas> professordisciplinasapagar;
    /**
     * Creates new form frmCadProfessorDisciplina
     */
    public frmProfessorDisciplina(int cod) {
        initComponents();
      
        professordisciplinasapagar = new LinkedList<>();
        disciplina = new Disciplina();
        cursos = new LinkedList<>();
        cursodao = new CursoDAO();
        pessoadao = new PessoaDAO();
        disciplinadao = new DisciplinaDAO();
        professordao = new ProfessorDAO();
        professor = professordao.Abrir(cod);
        professordisciplinadao = new ProfessorDisciplinaDAO();
        professordisciplinas = professordisciplinadao.ListarTodas(cod);
        cursos = cursodao.ListarTodos();
        pessoa = pessoadao.Abrir(professor.getCodpessoa());
        
        lblNome.setText(pessoa.getNome());
        
        cbxcurso.removeAllItems();
        for (Curso curso : cursos) {
            cbxcurso.addItem(curso);
        }

        curso = (Curso) cbxcurso.getItemAt(0);
        
        cbxdisciplina.removeAllItems();
        for (Disciplina disciplina : disciplinadao.ListarDisciplina(curso.getCodcurso())) {
            cbxdisciplina.addItem(disciplina);
        }
        
        disciplinatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurso = new javax.swing.JLabel();
        cbxcurso = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDisciplinas = new javax.swing.JTable();
        cbxdisciplina = new javax.swing.JComboBox();
        lblDisciplina = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        lblTextoduracao = new javax.swing.JLabel();
        lblNome_professor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Disciplinas do Professor");

        lblCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCurso.setText("SELECIONE O CURSO: ");

        cbxcurso.setToolTipText("");
        cbxcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxcursoActionPerformed(evt);
            }
        });

        tblDisciplinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDisciplinas);

        lblDisciplina.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDisciplina.setText("SELECIONE A DISCIPLINA:");

        btnAdicionar.setBackground(new java.awt.Color(98, 155, 88));
        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_add.fw.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnRemover.setBackground(new java.awt.Color(98, 155, 88));
        btnRemover.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_remove.fw.png"))); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        lblTextoduracao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblNome_professor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNome_professor.setText("NOME DO PROFESSOR:");

        lblNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnSalvar.setBackground(new java.awt.Color(98, 155, 88));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_confirm.fw.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(183, 70, 53));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_cancel.fw.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCurso)
                                .addGap(18, 18, 18)
                                .addComponent(cbxcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblDisciplina)
                                .addGap(18, 18, 18)
                                .addComponent(cbxdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTextoduracao))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome_professor)
                                .addGap(42, 42, 42)
                                .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(btnAdicionar)
                                .addGap(93, 93, 93)
                                .addComponent(btnRemover))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnSalvar)
                        .addGap(161, 161, 161)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome_professor)
                    .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblTextoduracao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCurso)
                            .addComponent(cbxcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxdisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDisciplina))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void disciplinatable() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Curso");
        model.addColumn("Disciplina");
        for(ProfessorDisciplinas pf : professordisciplinas){
            Vector v = new Vector();
            Disciplina disciplina = new Disciplina();
            disciplina = disciplinadao.Abrir(pf.getDisciplina().getCoddisciplina());
            Curso curso = new Curso();
            curso = cursodao.Abrir(disciplina.getCurso().getCodcurso());
            pf.setDisciplina(disciplina);
            pf.setProfessor(professor);
            v.add(curso);
            v.add(pf);
            model.addRow(v);
        }
        
        tblDisciplinas.setModel(model);
    
    }
        
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja adicionar esta disciplina para este professor?") == 0) {
            ProfessorDisciplinas professordisciplina = new ProfessorDisciplinas();
            disciplina = (Disciplina) cbxdisciplina.getSelectedItem();
            professordisciplina.setDisciplina(disciplina);
            professordisciplina.setProfessor(professor);
            if(professordisciplinas.contains(professordisciplina)){
                JOptionPane.showMessageDialog(RootPane, "Disciplina já adicionada!");
            } else {
                professor.addDisciplinas(disciplina);
                professordisciplinas.add(professordisciplina);
                JOptionPane.showMessageDialog(RootPane, "Disciplina adicionada com sucesso!");
                disciplinatable();
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if (tblDisciplinas.getSelectedRow() >= 0){
            if (JOptionPane.showConfirmDialog(RootPane, "Deseja remover esta disciplina deste professor?") == 0) {
                ProfessorDisciplinas professordisciplina = new ProfessorDisciplinas();
                professordisciplina = (ProfessorDisciplinas) tblDisciplinas.getValueAt(tblDisciplinas.getSelectedRow(), 1);
                professordisciplinas.remove(professordisciplina);
                professor.removeDisciplinas(professordisciplina.getDisciplina());
                professordisciplinasapagar.add(professordisciplina);
                disciplinatable();
            } else {
                JOptionPane.showMessageDialog(RootPane, "Ação cancelada!");
            }
        } else {
            JOptionPane.showMessageDialog(RootPane, "Selecione uma disciplina por favor!");
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja salvar as disciplinas deste professor?") == 0){
            for(ProfessorDisciplinas pd : professordisciplinas){
                professordisciplinadao.Salvar(pd);
            }
            
            for(ProfessorDisciplinas pd : professordisciplinasapagar){
                professordisciplinadao.Apagar(pd);
            }
           
            JOptionPane.showMessageDialog(RootPane, "Disciplinas do professor salvas!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(RootPane, "Ação cancelada!");
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(RootPane, "Deseja Cancelar?") == 0){
            JOptionPane.showMessageDialog(RootPane, "Ação Cancelada!");
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cbxcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxcursoActionPerformed
        // TODO add your handling code here:
        Curso curso = new Curso();
        curso = (Curso) cbxcurso.getSelectedItem();
        cbxdisciplina.removeAllItems();
        for (Disciplina disciplina : disciplinadao.ListarDisciplina(curso.getCodcurso())) {
            cbxdisciplina.addItem(disciplina);
        }
    }//GEN-LAST:event_cbxcursoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox cbxcurso;
    private javax.swing.JComboBox cbxdisciplina;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDisciplina;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome_professor;
    private javax.swing.JLabel lblTextoduracao;
    private javax.swing.JTable tblDisciplinas;
    // End of variables declaration//GEN-END:variables

    
}
